version: '3.8'

services:
  healthmed.webapi:
    image: healthmed.webapi
    build:
      context: .
      dockerfile: src/HealthMed.WebApi/Dockerfile
    depends_on:
      healthmed_sqlserver:
        condition: service_healthy
      healthmed_rabbitmq:
        condition: service_healthy
    environment:
      - ConnectionStrings__HealthMed=Server=healthmed_sqlserver;Database=HealthMed;User=sa;Password=Senha@123;TrustServerCertificate=True
      - RabbitMq__Host=healthmed_rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    ports:
      - "8080:8080"
      - "8081:8081"

  healthmed_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: healthmed_sqlserver
    environment:
      SA_PASSWORD: "Senha@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql  # Mapeia o volume
    healthcheck:
      test: [ "CMD-SHELL", "pidof sqlservr || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 30s

  healthmed_rabbitmq:
    image: rabbitmq:3-management
    container_name: healthmed_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  sqlserver_data: