apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmed-rabbitmq
  labels:
    app: healthmed-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthmed-rabbitmq
  template:
    metadata:
      labels:
        app: healthmed-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          livenessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5