apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmed-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthmed-auth-api
  template:
    metadata:
      labels:
        app: healthmed-auth-api
    spec:
      containers:
        - name: authapi
          image: gabrielantognoli/healthmed.authapi:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10